modLoader = "javafml"
loaderVersion = "[36,)"
license = "MPL-2.0"
issueTrackerURL = "https://github.com/Porcelain-south/BetterPMC/issues"

[[mods]]
modId = "bpmc"
version = "1.2.2"
displayName = "BetterPMC"
authors = "SuSen36"
credits = "\nArtist: GrassCarp, DLlover, Echoes_ACT\nData Pack: 136"
logoFile = "logo.png"
description = 'This is an add-on mod about "HTPVZ Mod" version 1.16.5'

[[dependencies.bpmc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,) "
ordering = "NONE"
side = "BOTH"

[[dependencies.bpmc]]
modId = "forge"
mandatory = true
versionRange = "[36.2.39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bpmc]]
modId = "pvz"
mandatory = true
versionRange = "[0.6.3,)"
ordering = "NONE"
side = "BOTH"
